
spring.application.name=business-agent

server.port=${PORT:8080}

monday.api.url=https://api.monday.com/v2
monday.api.token=${MONDAY_API_TOKEN}


monday.deals.board.id=5030094204
monday.workorders.board.id=5030097601
gemini.api.key=${GEMINI_API_KEY}

