
spring.application.name=business-agent

server.port=${PORT:8080}

monday.api.url=https://api.monday.com/v2
monday.api.token=${MONDAY_API_TOKEN}


monday.deals.board.id=5030103593
monday.workorders.board.id=5030103583
groq.api.key=${GROQ_API_KEY}

