
spring.application.name=business-agent

server.port=8080

monday.api.url=https://api.monday.com/v2
monday.api.token=eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjY4NDg3MjU1MywiYWFpIjoxMSwidWlkIjoxMTA0NzE4NTEsImlhZCI6IjIwMjYtMDctMjFUMDk6MjA6NTAuMDAwWiIsInBlciI6Im1lOndyaXRlIiwiYWN0aWQiOjM2MTMxMzk3LCJyZ24iOiJhcHNlMiJ9.WbW9xW-zpuflr4b2DvWos1M4jx7ka0VYUAsRjZXzqKQ

monday.deals.board.id=5030094204
monday.workorders.board.id=5030097601

gemini.api.key=AIzaSyDAbTv-45MbJIg3hJv7cY2om_wIwaMC36A